### ISSUE TITLE
Zoom to fit should take larger dimension (width/height) into account

### ISSUE THREAD

**Issue by jhrcek** [sverweij/atom-graphviz-preview-plus#10]
Hello,
thank you for this wonderful plugin, it works like charm :-)

I just have one minor issue: the "Zoom to fit" button only takes graph width into account.
In case I have graph whose height is bigger that width, it's not displayed in its entirety, it's only zoomed so that width fits (see screenshot).

This has 2 possible solutions in my opinion:
1) replace "Zoom to fit" with 2 buttons: "Zoom to fit width" and "Zoom to fit height"
2) make "Zoom to fit" take bigger of width/height into account

![issue](https://cloud.githubusercontent.com/assets/2716069/21680214/ab0e7a4a-d348-11e6-9892-ecce5621694b.png)

**Comment by sverweij** [comment]
You're right. I'll change _zoom to fit_ to match the behavior of atom's image-preview package - which matches your second option IIRC.

**Comment by sverweij** [comment]
@jhrcek I've published version 1.2.1 on atom.io this morning. When you click 'Zoom to fit'  it now also takes height into account.

![zoom-to-fit-vertical](https://cloud.githubusercontent.com/assets/4822597/21740310/d2adc69a-d4b6-11e6-9b5e-86528cbbe51b.gif)

It's not perfect yet; resizing the tab vertically does not adjust the image size (vertically it does, as you can see in the screencast above). 

I'll tweak it some more in upcoming releases, but didn't want to withhold this improvement.

**Comment by jhrcek** [comment]
Thank you for the quick fix! It's perfect for my use case already :-)

**Comment by sverweij** [comment]
Great! I'll close this issue then and put further improvements on the [roadmap](https://github.com/sverweij/atom-graphviz-preview-plus/projects/1)
