### ISSUE TITLE
Question: How easy do you think it would be to build a plugin for inline display of graphviz template strings?

### ISSUE THREAD

**Issue by sebinsua** [sverweij/atom-graphviz-preview-plus#11]
How easy do you think it would be to build a plugin for inline display of `dot` template strings?

Like, for example:

```javascript

const someObject = dot`
  graph g {
    farmer -> farm -> animal
  }
`;

```

I'm aiming to create a plugin which can then display this inline, sort of like how [`preview-inline`](https://atom.io/packages/preview-inline) works but within JavaScript code (and perhaps also markdown but with a different syntax for capturing).

This isn't a feature request. But since I've never written an Atom plugin, I wonder if you have any insight on whether this will be possible and if-so what the best way of doing so would be?

**Edit:** If you're wondering why anybody would want to do this, my reason is that I'm experimenting with using the [`dot` language as a visual method of representing interactions with graph databases](https://github.com/sebinsua/graphviz-config-template). It's a bit of a crazy idea but I like the idea that somebody could quickly look through a file to see the different networks it can save, update, etc.

**Comment by sverweij** [comment]
Cool idea.

How hard this is to implement (i.e. on a scale from 1-10) I can't answer - there's too much unknowns for me to assess that. I can give you some ammunition that might help you decide for yourself, though.

### Is it possible?
Yes.
- Atom is super friendly to customise.
- Transforming dot to graphics is relatively easy. You can [wrap the command line version](https://github.com/sverweij/atom-graphviz-preview-plus/blob/master/lib/wrap-dot.coffee) or [use viz.js](https://github.com/sverweij/atom-graphviz-preview-plus/blob/master/lib/renderer.coffee). I'd go with wrapping the command line. Its performance is better, it's more stable and it doesn't need hacks to get it to work. The nice thing about viz.js (=graphviz compiled to javascript with emscripten) is that it is easier to package.
- I don't know how to do the inlining, but there seem to be a few solutions around to copy and mold to your needs 

### How to start writing an atom plugin?
This is how I approached it:
- **Steal an existing one** that has functionality that comes close to what you want (e.g. the preview-inline you mentioned or hydrogen), and tweak it until it's doing what you want it to.
- The **[atom docs](https://atom.io/docs)** helped me understand the various bits & bobs of atom packages.
- If possible **use JavaScript** as implementation language (unless you're already comfy with coffee-script).
  - CoffeeScript looked to be the language of choice for atom, but JavaScript (es6!) works just as well out of the box.
  - CoffeeScript isn't hard to learn, but it is an extra new thing in a new environment.
  - There's a lot of examples in CoffeeScript around still, but it's easy to read and if necessary you can translate it to js (e.g. on [coffeescript.org](http://coffeescript.org))

**Comment by sverweij** [comment]
( @sebinsua did that help? )

**Comment by sebinsua** [comment]
That was helpful thanks!

I'll close. :)
