### ISSUE TITLE
Could you please also enable plugin for .gv file

### ISSUE THREAD

**Issue by deathrush** [sverweij/atom-graphviz-preview-plus#12]
A `.dot` file always is displayed with Microsoft Office icon on Windows, so I prefer to use `.gv` suffix which same as GVEdit.

**Comment by sverweij** [comment]
Hey @deathrush, thanks for your suggestion. 

For associating atom-graphviz-preview-plus relies on [language-dot](https://github.com/AdoPi/language-dot), the grammar for graphviz in atom. language-dot is currently associated to `dot` and `DOT`

We can try a PR on language-dot to extend that to `.gv` ...

The internal mechanics  to support `.gv` in atom-graphviz-preview-plus are already in place; 
in the [keymaps](https://github.com/sverweij/atom-graphviz-preview-plus/blob/master/keymaps/graphviz-preview-plus.cson#L1) & the [main](https://github.com/sverweij/atom-graphviz-preview-plus/blob/master/lib/main.coffee#L90) module.

**Comment by deathrush** [comment]
Thanks
