### ISSUE TITLE
Uncaught TypeError: Cannot read property 'css' of null

### ISSUE THREAD

**Issue by shigeru333** [sverweij/atom-graphviz-preview-plus#15]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [graphviz-preview-plus](https://github.com/sverweij/atom-graphviz-preview-plus) package 1.4.1

### Stack Trace

Uncaught TypeError: Cannot read property 'css' of null

```
At /Users/sokumura/.atom/packages/graphviz-preview-plus/lib/graphviz-preview-plus-view.js:470

TypeError: Cannot read property 'css' of null
    at GraphVizPreviewView.adjustZoom (/packages/graphviz-preview-plus/lib/graphviz-preview-plus-view.js:470:54)
    at GraphVizPreviewView.zoomOut (/packages/graphviz-preview-plus/lib/graphviz-preview-plus-view.js:462:14)
    at /packages/graphviz-preview-plus/lib/graphviz-preview-plus-view.js:101:51)
    at HTMLButtonElement.dispatch (/packages/graphviz-preview-plus/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/packages/graphviz-preview-plus/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:06.5.0 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:42.6.0 graphviz-preview-plus:toggle (input.hidden-input)
```

### Non-Core Packages

```
graphviz-preview-plus 1.4.1 
language-dot 1.7.0 
```

**Comment by sverweij** [comment]
hi @shigeru333, thanks for reporting this! 

Can you share the graphviz dot input (and/ or steps you take) you to get this error with?

I've reproduced the problem ((1) freshly start with an invalid graphviz dot source, (2) open the preview and (3) hit one of the zoom buttons) - but can't be sure it's the same you've got.

**Comment by sverweij** [comment]
@shigeru333 I've made a fix for what I deduced to be the problem - I'll publish it shortly as version 1.4.2 (when you're reading this that is probably done already). 

Please let me know if it solved the issue for you as well.
