### ISSUE TITLE
persistent "syntax error in line 1..." after forgetting " once

### ISSUE THREAD

**Issue by axe312ger** [sverweij/atom-graphviz-preview-plus#16]
# Problem

This error often occurs after another error was fixed in the dot-code. Instead of drawing the graph (since the code is valid now) it shows:

```
Error: syntax error in line 1 near '"'
```
There is not even a `"` in line 1

When I reduce my valid graph code to a simple:
```r
A -> B
```

the following error shows up:
```
TypeError: Cannot read property 'clientHeight' of undefined
```

## Workaround

Restarting atom solves the problem and renders the valid graph code.

## Steps to reproduce:
Start a new graph:
```
digraph G {
  "A" -> "B"
}
```
Change to:
```
digraph G {
  "A" -> "B" [label="foo]
}
```
This is broken, ofc. so fix it:
```
digraph G {
  "A" -> "B" [label="foo"]
}
```
Code is valid, but now the error with `"` one line 1 shows up.

I would love a fix, your addon is super awesome and makes atom a incredible DOT editor <3

**Comment by sverweij** [comment]
Hmm. I had a workaround for exactly this problem until 1.4.0 Couldn't reproduce it with the latest version of viz.js so removed the workaround. 

Thanks @axe312ger for bringing this to my attention. I'll re-apply the workaround and release a patch version a.s.a.p.

**Comment by axe312ger** [comment]
awesome!!!

**Comment by sverweij** [comment]
@axe312ger could you share 
- the version of graphviz-preview-plus you're using (I've assumed 1.4.1). 
- whether or not you're using the dot command line option (and if so: which version of dot)
- (just to be sure) the version of atom you're using

(I've tried to reproduce your test scenario on my machine with v1.4.1 but I can't get it to fail - which either means I'm doing something wrong or our setups are slightly different - in any case I want to stamp this bug out).

**Comment by axe312ger** [comment]
I am not with my computer for now, but can tell you it should have been the most recent version of Atom and your plugin since I discovered the plugin yesterday and my Atom was up 2 date.

I did not even open the configuration pane, just plane default settings :)

Helps?

**Comment by sverweij** [comment]
That already helps in narrowing down analysing the cause (although precise version numbers are still welcome).

It also puzzles me a bit. Only older versions of `viz,js` (the package gv-p-p uses for dot rendering) yield that unrecoverable error. And gv-p-p has the latest one (1.8.0) as a dependency. :confused:.

A quick fix would be to re-apply the workaround I mentioned in my first response. But it wouldn't solve the underlying problem - which is that an older version of viz.js is loaded in your environment than should be possible as per specified in the plugin's dependencies.

An explanation I can come up with is that there's another version of `viz.js` already loaded within the atom context, e.g. loaded by another plugin. If that's the case I can put some defenses in place (which will slightly impact the time to do the first rendition). I'll test this hypothesis.

**Comment by axe312ger** [comment]
```
$ atom -v
Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

```
$ apm list
...
├── graphviz-preview-plus@1.4.0
...
```

```
$ dot -v
dot - graphviz version 2.40.1 (20161225.0304)
```

```
$ cd /Users/nanananananana/.atom/packages/graphviz-preview-plus
$ npm list
graphviz-preview-plus@1.4.0 /Users/bene/.atom/packages/graphviz-preview-plus
├─┬ atom-package-deps@4.6.0
│ ├─┬ atom-package-path@1.1.0
│ │ └── sb-callsite@1.1.2
│ ├─┬ sb-exec@3.1.0
│ │ ├─┬ consistent-env@1.3.1
│ │ │ └── lodash.uniq@4.5.0 deduped
│ │ ├── lodash.uniq@4.5.0
│ │ └─┬ sb-npm-path@2.0.0
│ │   ├── sb-memoize@1.0.2
│ │   └── sb-promisify@2.0.2 deduped
│ ├─┬ sb-fs@3.0.0
│ │ ├── sb-promisify@2.0.2
│ │ └─┬ strip-bom-buf@1.0.0
│ │   └── is-utf8@0.2.1
│ └── semver@5.3.0
├─┬ atom-space-pen-views@2.2.0
│ ├── fuzzaldrin@2.1.0
│ └─┬ space-pen@5.1.2
│   ├─┬ grim@1.5.0
│   │ └─┬ emissary@1.3.3
│   │   ├─┬ es6-weak-map@0.1.4
│   │   │ ├─┬ d@0.1.1
│   │   │ │ └── es5-ext@0.10.23 deduped
│   │   │ ├─┬ es5-ext@0.10.23
│   │   │ │ ├─┬ es6-iterator@2.0.1
│   │   │ │ │ ├─┬ d@1.0.0
│   │   │ │ │ │ └── es5-ext@0.10.23 deduped
│   │   │ │ │ ├── es5-ext@0.10.23 deduped
│   │   │ │ │ └── es6-symbol@3.1.1 deduped
│   │   │ │ └─┬ es6-symbol@3.1.1
│   │   │ │   ├── d@1.0.0 deduped
│   │   │ │   └── es5-ext@0.10.23 deduped
│   │   │ ├─┬ es6-iterator@0.1.3
│   │   │ │ ├── d@0.1.1 deduped
│   │   │ │ ├── es5-ext@0.10.23 deduped
│   │   │ │ └── es6-symbol@2.0.1 deduped
│   │   │ └─┬ es6-symbol@2.0.1
│   │   │   ├── d@0.1.1 deduped
│   │   │   └── es5-ext@0.10.23 deduped
│   │   ├── mixto@1.0.0
│   │   ├─┬ property-accessors@1.1.3
│   │   │ ├── es6-weak-map@0.1.4 deduped
│   │   │ └── mixto@1.0.0 deduped
│   │   └── underscore-plus@1.6.6 deduped
│   ├── jquery@2.1.4
│   └── underscore-plus@1.6.6 deduped
├─┬ fs-plus@3.0.0
│ ├── async@1.5.2
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├─┬ rimraf@2.6.1
│ │ └─┬ glob@7.1.2
│ │   ├── fs.realpath@1.0.0
│ │   ├─┬ inflight@1.0.6
│ │   │ ├── once@1.4.0 deduped
│ │   │ └── wrappy@1.0.2
│ │   ├── inherits@2.0.3
│ │   ├─┬ minimatch@3.0.4
│ │   │ └─┬ brace-expansion@1.1.8
│ │   │   ├── balanced-match@1.0.0
│ │   │   └── concat-map@0.0.1
│ │   ├─┬ once@1.4.0
│ │   │ └── wrappy@1.0.2 deduped
│ │   └── path-is-absolute@1.0.1
│ └── underscore-plus@1.6.6 deduped
├─┬ underscore-plus@1.6.6
│ └── underscore@1.6.0
└── viz.js@1.3.0
```

helps? :)

**Comment by axe312ger** [comment]
Updated to 1.4.2 and the error does no more occur :)

**Comment by sverweij** [comment]
Thanks. 1.4.0 was still on viz.js 1.3.0 indeed. 1.4.1 and later are on 1.8.0 which doesn't have the error anymore.

The world makes sense again 😅

**Comment by axe312ger** [comment]
awesome
