### ISSUE TITLE
Option for Zoom to Width

### ISSUE THREAD

**Issue by rhelms** [sverweij/atom-graphviz-preview-plus#21]
As well as the Zoom to fit, it would be nice to have a Zoom to width, so long graphs can be previewed by scrolling instead of squinting.

**Comment by sverweij** [comment]
Thanks for this suggestion @rhelms - I can see how this would be useful.

**Comment by sverweij** [comment]
See PR ☝️ . Will merge & publish in the coming days.

**Comment by sverweij** [comment]
Published to atom.io @rhelms give it a try and tell me what you think

**Comment by rhelms** [comment]
The end result looks good, although it takes a few clicks to get it to stick. When the "to width" option is selected via the click method, it doesn't always kick in the first time (using v1.5.1)

Steps to reproduce:
1. Click Zoom to fit
2. Right-click Zoom to fit, and mouse to Zoom > "to width". At this point, it appears that no zoom is being applied.
3. Right-click Zoom to fit, and mouse to Zoom > "to width". Once reapplied, the preview has the zoom to width applied.

The same happens when you use the Ctrl-8 shortcut.

Ctrl-9 "to fit" works the first time.
Ctrl-0 "reset" works the first time.
Ctrl-7 "to height" takes two attempts from a reset to get a flush fit. For my particular preview, the first attempt will have a small gap between the top container border and the top of the preview, and a small gap between the bottom container border and the bottom of the preview. The second attempt will align correctly and remove that gap.
Ctrl-8 "to width" takes one attempt from a reset. 
Ctrl-8 "to width" takes two or three attempts from a "to fit". The first attempt removes any sort of zoom. The second attempt resizes with a small gap between the left container border and the left preview edge, and a small gap between the right container border and the right preview edge. The third attempt will get it right. Whether it takes two or three attempts depends on the width of the preview container.

**Comment by rhelms** [comment]
I should be a little more enthusiastic about my response. This functionality is fantastic, and it has definitely aided my vision when looking at tall images. Thank you very much for implementing it.

**Comment by sverweij** [comment]
Thanks for the feedback & detailed issue repro report @rhelms - it's easy to reproduce with that in hand. The number of zoom options has apparently outgrown the initial approach - I'll see if I can iron them out.
