### ISSUE TITLE
Can't open url defined for node

### ISSUE THREAD

**Issue by lolpany** [sverweij/atom-graphviz-preview-plus#25]
When describing node like this
` node [URL="http://google.com"]`
it rendered as link and cursor changes when hover over it, but on click nothing happens.
It would be awesome, if file (for `file:///` scheme) or link (for `http://` or `https://` schemes) opened up on click.

**Comment by sverweij** [comment]
Thanks for raising this.

I just checked what happens: GraphViz generates links in the 'proper' svg way to do so, with the `xlink` xml namespace e.g.

```svg
<a xlink:href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" xlink:title="don't give up" xmlns:xlink="http://www.w3.org/1999/xlink">
  <ellipse fill="none" stroke="#000000" cx="62.5331" cy="-18" rx="62.5663" ry="18"></ellipse>
  <text text-anchor="middle" x="62.5331" y="-13.8" font-family="Times,serif" font-size="14.00" fill="#000000">don't give up</text>
</a>
```

However, atom doesn't seem to be able to cope with these. It's an issue in other atom packages as well. Try opening the svg above with svg-preview and the links won't be clickable either.
It looks like an oversight from the atom team it doesn't work, but maybe there's a legit reason for it.

I see two ways to go about this
- Introduce a hack that - as long as the svg lives in the atom preview window - replaces any `xlink:href` with a `href` (or dirtier: adds it).
- Have atom fix it. 

=> What is the case you need this functionality for?

**Comment by lolpany** [comment]
Thanks fro reply.
The reason is i want to embed rickroll videos into may diagrams.
I think that better atom fix it.

**Comment by sverweij** [comment]
Embedding rickroll videos sounds like a noble cause.  Fix on its way ☝️.

(srsly: I expect links to work in my preview window - thanks again for raising this issue. The better solution is that atom fixes it, obviously - but until that occurs a workaround is the only thing I can do. B.t.w. the svg you would export will not contain the workaround).
