### ISSUE TITLE
Render graphs embedded in Markdown

### ISSUE THREAD

**Issue by hjsl** [sverweij/atom-graphviz-preview-plus#28]
Hi,

Thanks for a very nice plugin!

I use Markdown a lot to document technical content (as do many others, I would suspect :-) ). It would be super-helpful to be able to make simple graphs _inline_ in these documents, and have them being rendered as actual graphs in the Markdown preview. It could be e.g. a simple class diagram or flowchart which helps the reader understand the text.

Currently, if I want a graph inside a Markdown document, I have to create the graph elsewhere, export it as an image, and then embed that image. That works ok, but it is a pain when you need to change that graph. Also, you need three files (Markdown, source graph, graph image) when I really just want one.

I imagine it would look something like:

    # Title
    My Markdown document.
    
    ```graphviz
    graph {
      a -- b
      a -- c
    }
    ```

I totally understand if you feel this is out of scope for your plugin, but hey, one can dream, right? 😄

**Comment by sverweij** [comment]
shd101wyy 's _markdown-preview-enhanced_ supports this. I haven't tried it, but it looks promising: https://shd101wyy.github.io/markdown-preview-enhanced/#/diagrams?id=graphviz

**Comment by hjsl** [comment]
Ah, I had not seen that! Seems to work well. Thanks. :-)
