### ISSUE TITLE
Can't save files as PNG or SVG

### ISSUE THREAD

**Issue by Muldec** [sverweij/atom-graphviz-preview-plus#30]
Hi !

For some reason, I'm unable to save graphs as PNG or SVG (copy as SVG works). The operation silently fails.

This happen for all graphs, even simple one (a unique node)

Atom version : 1.24.0 x64 on Windows 10
atom-graphviz-preview-plus version : 1.5.3 

I tested with and without graphviz command line : no change

**Comment by sverweij** [comment]
Hi - thanks for reporting!

Do you have the graphviz source on which this fails?
(or if you can't share that - the dimensions of the resulting graph?)

**Comment by Muldec** [comment]
Hi,

Sure, here is the source

`strict digraph G {
    rankdir="LR"
    compound=true fontname="arial"
    label="General view"
    //Common Styles
    node [fontname="arial", fontsize=12, fontcolor="blue", fillcolor=white, style="filled", shape="box"]
    edge [fontname="arial", fontcolor="#AAAAAA"]

    subgraph clusterFO {
        bgcolor="blue" fontcolor="white"
        label="front office"

        UI
        XLSFileMgr [label="Excel impot/Export"]
	}
    {
        newrank=true
        rank=same

        subgraph clusterBO {
            bgcolor="purple" fontcolor="white" style=solid
            label="back office"

    		APIs
    	}

        PostgreSQL  [shape="cylinder", fillcolor="yellow",height=1]
    }

    subgraph clusterSAP {
        label="Mid"
        bgcolor="aquamarine"
        Calculation [label="Calculation"]
        DataImport [label="Data Import"]
    }

    APIs -> PostgreSQL [style="dashed" dir="both" arrowtail="inv" arrowhead="crow" label="read / write" ltail=clusterBO constraint=false]
    UI -> APIs [arrowhead="odot" label="call" ltail=clusterFO]
    APIs -> Calculation [arrowhead="odot" label="call" ltail=clusterBO constraint=false]
    DataImport -> PostgreSQL [style="dashed" arrowhead="crow" label="read"]
}
`

Note that I tried to use a very simple graph and the save as function didn't work either :

`strict digraph G {
    node1
}`

**Comment by sverweij** [comment]
Thanks!

If it doesn't work for simple graphs anymore probably something changed in
one of the latest atom releases - I'll try and have a look during the
weekend.

**Comment by sverweij** [comment]
Just tried to reproduce it - have a slightly different config (atom 1.25 on windows 7). There it works fine (see attached ani-gif below).

I _do_ see the thing gvpp uses for saving gets a deprecation warning. I'll fix that a.s.a.p. (~ this weekend if nothing weird happens). Not sure that's the cause, however; there's a surprising amount of things that can go wrong with a simple thing as vector -> bitmap conversion () & saving (e.g. file system permissions). I do consider silent fails to be bugs, though. I'll try & see if I can reproduce it on a win10 machine or image (if I can get my hand on one).

![save-as-png-bug-reproduction-attempt](https://user-images.githubusercontent.com/4822597/37116036-425d3298-224d-11e8-8d57-d4d234f09241.gif)

**Comment by sverweij** [comment]
@Muldec I found the root cause - atom 1.24.0 has a bug in the saveAs dialog that made it fail silently always: https://github.com/atom/atom/issues/16801 .

Seems to be fixed as of atom 1.24.1. 

-> could you check if upgrading your atom version to 1.24.1 (or higher) solves the issue for you?

That's also the reason I couldn't reproduce it in atom 1.25 (there the bug is fixed) or 1.23 and before (there the bug didn't exist yet).

**Comment by Muldec** [comment]
@sverweij You are right ! 

The latest version of Atom solved the issue.

Thanks for the information.
