### ISSUE TITLE
Escape HTML in error dialog (script injection attack!)

### ISSUE THREAD

**Issue by maul-esel** [sverweij/atom-graphviz-preview-plus#36]
The error dialog does not escape HTML. Therefore it is possible to inject HTML and even execute javascript when previewing a file.

Besides potentially annoying effects -- e.g. the syntax is not fully displayed, because it is partially interpreted as HTML, making it more difficult to find a syntax error -- this is probably quite the security issue.

## Minimal example
```
digraph example {
  "test" [label=<<script type="text/javascript"> alert("executing code!");</script>>]
}
```
When previewing this file, an alert box displaying "executing code!" is shown.

**Comment by sverweij** [comment]
... and published as version 1.5.6 on [atom.io](https://atom.io/packages/graphviz-preview-plus)

(I'll close the issue for now, considering it fixed - but feel free to re-open if you think otherwise!

**Comment by maul-esel** [comment]
Fixed the example, and I didn't manage to find another way to break it so far. Personally, I'd have used some library function, to be a bit safer (I think you're using underscore, so maybe [escape](https://underscorejs.org/#escape)?), but it seems they do pretty much the same (except for more characters).

Thanks for the fix, and the great response time :+1:

**Comment by sverweij** [comment]
@maul-esel thanks for re-testing & feedback so quickly - much appreciated.

Agree with the sentiment to use something standard for it - I'll probably replace the current fix with that (`_.escape` sounds good like a good suggestion) later, but this is what I could come up  within the span of a lunch break.
